/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GamePolicyServices.framework/Versions/A/GamePolicyServices
 */

@interface GPSGameFilter : NSObject

+ (BOOL)filterApplication:(id)arg1 withLaunchingApplication:(struct __LSASN { }*)arg2 sessionID:(int)arg3;
+ (id)launcherBundleIdentifiers;

@end
