/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GamePolicy.framework/Versions/A/GamePolicy
 */

@interface _GamePolicyAssertion_Attribute : NSObject <NSSecureCoding>

@property (nonatomic, readonly) NSString *description;

+ (BOOL)supportsSecureCoding;

- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end
