/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GamePolicy.framework/Versions/A/GamePolicy
 */

@interface _TtCCC10GamePolicy19GamePolicyAssertion9Attribute10Privileged : _GamePolicyAssertion_Attribute

@property (nonatomic, readonly) NSString *description;

+ (BOOL)supportsSecureCoding;

- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;

@end
