/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GamePolicy.framework/Versions/A/GamePolicy
 */

@interface GamePolicy.GamePolicyAppXPC : NSObject

+ (id)GamePolicyAppClientInterface;
+ (id)GamePolicyAppServerInterface;

- (id)init;

@end
