/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GamePolicy.framework/Versions/A/GamePolicy
 */

@interface GPGameMonitorEnvoy : NSObject

+ (id)shared;
+ (id)sharedInstance;

- (id)init;

@end
