/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GamePolicy.framework/Versions/A/GamePolicy
 */
// GPProcessInfo.h
@interface GPProcessInfo : NSObject {
    struct { 
        unsigned int val[8]; 
    }  _auditToken;
    BOOL  _identifiedGame;
}

@property struct { unsigned int x1[8]; } auditToken;
@property (getter=isIdentifiedGame) BOOL identifiedGame;

+ (id)processInfo;

- (struct { unsigned int x1[8]; })auditToken;
- (id)init;
- (BOOL)isIdentifiedGame;
- (void)setAuditToken:(struct { unsigned int x1[8]; })arg1;
- (void)setIdentifiedGame:(BOOL)arg1;

@end
