/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GamePolicy.framework/Versions/A/GamePolicy
 */
//GPProcessMonitor.h
@interface GPProcessMonitor : NSObject {
    struct { 
        unsigned int val[8]; 
    }  _auditTokenForCurrentProcess;
    GPProcessInfo * _currentProcessInfo;
    BOOL  _invalidated;
    NSLock * _lock;
    NSObject<OS_dispatch_queue> * _queue;
    id  _updateHandler;
}

+ (struct { unsigned int x1[8]; })auditTokenForCurrentProcess;
+ (id)monitorForCurrentProcess;

- (void).cxx_destruct;
- (void)_onqueue_requestCurrentProcessInfo;
- (id)init;
- (void)setUpdateHandler:(id)arg1;

@end
